src/app/Ligi.Security/SingleTenantOwinSystemWeb/Areas/UserAccount/Controllers/ChangePasswordController.cs
using BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Controllers
{
    //[Authorize]
    public class ChangePasswordController : Controller
    {
        UserAccountService userAccountService;
        public ChangePasswordController(UserAccountService userAccountService)
        {
            this.userAccountService = userAccountService;
        }
        
        public ActionResult Index()
        {
            if (!User.HasUserID())
            {
                return new HttpUnauthorizedResult();
            }

            var acct = this.userAccountService.GetByID(User.GetUserID());
            if (acct.HasPassword())
            {
                return View(new ChangePasswordInputModel());
            }
            else
            {
                return View("SendPasswordReset");
            }
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ChangePasswordInputModel model)
        {
            if (!User.HasUserID())
            {
                return new HttpUnauthorizedResult();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.ChangePassword(User.GetUserID(), model.OldPassword, model.NewPassword);
                    return View("Success");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendPasswordReset()
        {
            if (!User.HasUserID())
            {
                return new HttpUnauthorizedResult();
            }

            try
            {
                var acct = this.userAccountService.GetByID(User.GetUserID());
                this.userAccountService.ResetPassword(acct.Tenant, acct.Email);
                return View("Sent");
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View("SendPasswordReset");
        }
    }
}

src/app/Ligi.Security/SingleTenantOwinSystemWeb/Areas/UserAccount/Views/ChangePassword/Index.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangePasswordInputModel
@{
    ViewBag.Title = "Change Password";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary("Error")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        @Html.EditorForModel()

        <div class="buttons">
            <button>Change Password</button>
        </div>
    </fieldset>
}

src/app/Ligi.Security/SingleTenantOwinSystemWeb/Areas/UserAccount/Views/ChangePassword/SendPasswordReset.cshtml
@model BrockAllen.MembershipReboot.Mvc.Areas.UserAccount.Models.ChangePasswordInputModel
@{
    ViewBag.Title = "Set Password";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("SendPasswordReset", "ChangePassword"))
{
    @Html.ValidationSummary("Error")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        <p>
            Your account does not currently have a password. In order to set one,
            we will send an email to your registered address to confirm the password
            request.
        </p>
        <div class="buttons">
            <button>Send Request</button>
        </div>
    </fieldset>
}

src/app/Ligi.Security/SingleTenantOwinSystemWeb/Areas/UserAccount/Views/ChangePassword/Sent.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Email Sent</h2>
<p>
    The password request was sent. Check your email
    to confirm the password change.
</p>

src/app/Ligi.Security/SingleTenantOwinSystemWeb/Areas/UserAccount/Views/ChangePassword/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>
<p>
    Password changed successfully. 
    Click @Html.ActionLink("here", "Index", "Home") to return home.
</p>